name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Chạy mỗi ngày 1 lần
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: dinhkhangggg
          template: classic
          base: ""
          config_timezone: Asia/Ho_Chi_Minh
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
