name: Spotify Status Update

on:
  schedule:
    - cron: '*/5 * * * *' # Chạy tự động mỗi 5 phút
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Spotify Now Playing
        uses: mehranredrose/spotify-now-playing@v2
        with:
          client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
