name: WakaTime Status

on:
  schedule:
    # Chạy tự động mỗi 12 giờ
    - cron: "0 */12 * * *"
  workflow_dispatch: # Cho phép bấm chạy bằng tay

jobs:
  update-readme:
    name: Update WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: last_7_days
          LANG_COUNT: 5
          SHOW_TIME: true
          SHOW_TOTAL: true
